export const BASE_URL = "http://localhost:1337/";
export const ESTABLISHMENT_URL = `${BASE_URL}api/establishments/`;
export const ENQUIRY_URL = `${BASE_URL}api/enquiries/`;
export const CONTACT_URL = `${BASE_URL}api/contacts/`;
export const AUTH_URL = `${BASE_URL}api/auth/local/`;
export const ENQUIRY_PATH = "api/enquiries/";
export const CONTACT_PATH = "api/contacts/";
export const ESTABLISHMENT_PATH = "api/establishments/";
export const POPULATE = "?populate=*";
